# (PART) Preparedness Diagnosis {-}

# Introduction

In July 2014, the Conference of Heads of Government of the Caribbean Community (CARICOM), approved the CARICOM Strategic Plan 2015-2019 which articulated the need for a more results-focused approach to programme and project management, and committed the Caribbean Community Secretariat to establish a planning, monitoring and evaluation (M&E), and reporting system based on the principles of Results-Based Management (RBM). In executing the tenets of the Community Strategic Plan, all implementing partners have expressed concern about an _implementation deficit_. This has resulted in poor implementation of public policy and Regional Public Goods in many Member States, culminating in low rates of successful program and project implementation across the Community.

Efforts to address the _implementation deficit_, to promote a more results-focused approach to programme and project management, and to strengthen RBM in the Community commenced in 2016 with the engagement of the consulting firm Baastel, to develop the CARICOM RBM System and support its institutionalisation at the CARICOM Secretariat. In October 2019, the CARICOM Secretariat requested technical assistance^[With non-lending Technical Assistance (TA) the Bank helps clients to implement reform and/or strengthen institutions. Qualified TA activity must meet the following criteria: have a primary intent of enabling an external client to implement reform and/or strengthen institutions; be linked to a Bank unit with clear accountability for the service provided.]  from the World Bank’s Independent Evaluation Group (IEG) to continue these efforts by supporting CARICOM in strengthening a result-oriented culture across the Community, which includes three implementing partners, the Member States, Regional Institutions, and the CARICOM Secretariat.

As part of the collaboration, the IEG and CLEAR LAC under the Global Evaluation Initiative (GEI) agreed to provide technical assistance in the establishment and institutionalisation of RBM policies, in addition to the Secretariat, to three pilot Member States (Dominica, Jamaica, and Saint Lucia) and three pilot Regional Institutions (the Caribbean Development Fund, the Caribbean Examinations Council, and the CARICOM Implementation Agency for Crime and Security). These pilots will serve as champions to support capacity strengthening in the remaining Member States and Regional Institutions, in collaboration with IEG and the CARICOM Secretariat.

In order to establish a customize roadmap to strengthen the pilot´s RBM Systems, a Preparedness Diagnostic was identified as a first step of the collaboration to assess the level of maturity of the systems and identify specific contextual and organizational features and milestones to be achieved over a over a five-year period.

This report presents the findings from the Preparedness Diagnostic for Jamaica. The report provides information on the existing strengthens and opportunities to develop a sustainable RBM System in the Member State.

The report consists of six sections, including the introduction. [Section 2](#section2) will present Jamaica'sposition on the results of the Preparedness Diagnostic. [Section 3](#section3) presents the methodology (including the Theory of Change of this activity); the Preparedness Diagnostic stages; and the “Ideal RBM System,” which consists of a four-dimension benchmark for this assessment).

[Section 4](#section4) contains general and contextual information about Jamaica. This section also addresses the interest, expectations and challenges that may arise through the implementation of an RBM system using a whole of government approach. Additionally progress on the development of their RBM system based on the four dimensions is presented under this section.

[Section 5](#section5) presents the main findings highlighting the level of progress for Jamaica in each of the four dimensions, and a stakeholder’s analysis. Finally, [Section 6](#section&) introduces the process for building a contextualized roadmap for advancing a sustainable RBM system for Jamaica, as well as a stakeholders’ contribution analysis.

After reading this report, the reader will obtain a clear idea of the existing practices and elements to strength on and advance  towards achieving a sustainable RBM system based on key elements. The report may also be used to guide discussions among relevant stakeholders to support sensitization of key stakeholders in the area of  RBM practices; to share best practices with other Member States; as well as to promote existing promising  practices that are being implemented.

Specifically, within the framework of this collaboration, the report represents the main input for the development of the contextualized medium-term roadmaps which will be facilitated  through participatory workshops and engagements.

